apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-deployment
  namespace: fs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend-tag
  template:
    metadata:
      labels:
        app: recommend-tag
    spec:
      containers:
      - name: recommend-container
        image: 825958448855.dkr.ecr.ap-northeast-2.amazonaws.com/recommendation:17
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-service
  namespace: fs-service
spec:
  type: ClusterIP
  selector:
    app: recommend-tag
  ports:
    - port: 80
      targetPort: 8080
