apiVersion: apps/v1
kind: Deployment
metadata:
  name: recent-deployment
  namespace: fs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recent
  template:
    metadata:
      labels:
        app: recent
    spec:
      containers:
      - name: recent-container
        image: 825958448855.dkr.ecr.ap-northeast-2.amazonaws.com/recent:7
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: recent-service
  namespace: fs-service
spec:
  selector:
    app: recent
  ports:        
    - protocol: TCP 
      port: 80
      targetPort: 8080
