apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
  namespace: fs-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translate
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
      - name: translate-container
        image: 825958448855.dkr.ecr.ap-northeast-2.amazonaws.com/translate:29
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: translate-service
  namespace: fs-service
spec:
  selector:
    app: translate
  ports:        
    - protocol: TCP 
      port: 80
      targetPort: 8080
